### PR TITLE
Window tagging feature

### PR DESCRIPTION
**Pull request by reneklacan**
Hi Eric,

As I am coming from Awesome WM world, I found Spectacle very useful but I missed some kind of window tagging. It made sense to me to implement this feature right into the Spectacle.

This feature allows you to tag window with hot key and then go back to the tagged window even if it is on different desktop.

I find myself very productive using it so I wanted share it so I'm wandering if you are interested to integrate this kind of feature into the Spectacle.

This is updated preferences window with default hot keys:
screen shot 2014-12-23 at 02 06 32

### CODE REVIEW

**Comment by 21croissants** [comment]
Awesome feature :+1:

**Comment by reneklacan** [comment]
I'm glad you like it

**Comment by 21croissants** [comment]
@reneklacan Unfortunately you'll have to rebase your PR.

@eczarny I'd :heart:  to give a small :euro:  for spectacle, especially with such as feature. Would you setup something like a https://www.bountysource.com/ ?

**Comment by 21croissants** [comment]
@eczarny I'd :heart:  to give a small :euro:  for spectacle, especially with such as feature. Would you setup something like a https://www.bountysource.com/ ?

<EDIT> I had not seen the paypal donation button. Unfortunately, for various reasons I am allergic to paypal :crying_cat_face: 
As it's already working, you probably don't want to setup another system for donations.

**Comment by lpil** [comment]
Very cool, would be good to have this feature merged in. :)

**Comment by reneklacan** [comment]
@21croissants You are right, thanks, I did rebase.

**Comment by reneklacan** [comment]
@eczarny ?

**Comment by eczarny** [comment]
Sorry for the delay. The feature sounds nice, and I appreciate the effort @reneklacan put into it, but I'm not too excited about adding even more shortcuts. I'd rather err on the side of simplicity and keep this feature out of the binary distributions.

**Comment by lpil** [comment]
What do you think about including the feature, but not having any shortcuts assigned to it by default, making it opt-in?

Cheers,
Louis

**Comment by eczarny** [comment]
@lpil That's a good points. Let me think on it a bit!

**Comment by janniklorenz** [comment]
Another solution would be to assign on (global) master shortcut, which then listen to single keys.
For Example: I have to press the master shortcut, then maybe the up arrow key which is directly assign to an action.
What are you thinking about that?

**Comment by reneklacan** [comment]
@eczarny Thank you for answer. I think that If you don't want to add new shortcuts then @lpil's suggestion is way to go But if you just want to keep Spectacle feature simple and it makes sense not to include this feature.

**Comment by ProLoser** [comment]
I find this feature kind of silly and redundant to CMD+TAB which does the same thing.

**Comment by reneklacan** [comment]
Not really if you consider having 4 active windows so in the worst case you have to do CMD + 3xTAB and you have to actually look to see how many times you should tap. But if you know that your terminal is always ALT + 2 then it's just reflex and it can boost your productivity. Give it a chance and try it.

**Comment by ProLoser** [comment]
@reneklacan @eczarny honestly any window I ever need to get to quickly I already have a global shortcut for. Most apps allow you to assign global shortcuts to them, in fact, I think it's build into OSX.

* [Fatastical (calendar)](https://flexibits.com/fantastical): CTRL+CMD+F
* [TotalTerminal](http://totalterminal.binaryage.com/)/[iTerm2](http://technosophos.com/2011/11/14/configure-iterm2-act-visor.html) (terminal): CTRL+Tilde(~)
* [TotalFinder](http://totalfinder.binaryage.com/): OPTION+Tilde(~)
* [Task Manager / Gmail (fluid app)](http://fluidapp.com/): CTRL+CMD+T or G or whatever.

It just doesn't seem like the responsibility for a project that does window resizing to handle alt-tabbing as it will bloat project scope and create more work for the maintainer when there's always a constant risk of being overrun with, say, the current ~100 open issues.

**Comment by 21croissants** [comment]
@ProLoser  "silly" ? You mean, you don't see the value of this feature and you don't need it in your current workflow.

**Comment by ProLoser** [comment]
@21croissants read expanded response ^

**Pull request closed without merging**
