### PR TITLE
added pt-BR translation.

### PR DESCRIPTION
**Pull request by vitu**

### CODE REVIEW

**Comment by eczarny** [comment]
Thanks @vitu! I merged this but I did notice that the word "Copyright" in the InfoPlist.strings file was not translated. Mind following up with another pull request with the fix for that?

**Comment by vitu** [comment]
Hey Eric,

Apple itself doesn’t translate the word copyright in Brazilian Portuguese either. Take a look:


Thanks for the merge; I hope Spectacle users find the localization useful!

Best regards,

Victor Figueiredo
brlingo.com <http://www.brlingo.com/> | twitter <http://twitter.com/br_lingo> | facebook <https://www.facebook.com/BRLingo> | linkedin <https://br.linkedin.com/pub/victor-figueiredo/b4/930/546>

**Comment by eczarny** [comment]
The other translations in Spectacle do. Here is the "About" dialog in French:

image

**Comment by vitu** [comment]
So you want the translation (regardless of how the OS behaves) to have the word “copyright” localized as well?

**Comment by eczarny** [comment]
Exactly. That way it's consistent with the other translations.

Thanks!

**Comment by vitu** [comment]
Hi Eric,

It’s done!

**Pull request merged**
