### PR TITLE
Remove unused Items form MenuItem

### PR DESCRIPTION
**Pull request by janniklorenz**
Fix Issue #319.

### CODE REVIEW

**Comment by waynehoover** [comment]
Any chance this will get merged soon?

**Comment by janniklorenz** [comment]
I would love to, but i think the only one who can is @eczarny

**Comment by eczarny** [comment]
Out of curiosity, what happens if you try to use something like ⌘C as a Spectacle shortcut?

**Comment by janniklorenz** [comment]
⌘C won't work, you still get the "in use" message. ⌘G for example is one of the shortcuts related to this issue.

**Pull request merged**
