### PR TITLE
Fix issue that shortcutAction not set when load from JSON, close #630

### LINKED ISSUE #630: Shortcuts not work since commit 4391dcc
```objective-c
- (NSArray<SpectacleShortcut *> *)loadShortcutsWithAction:(SpectacleShortcutAction)action
{
  NSError *error;
  NSURL *shortcutsURL = findShortcutsFileURL(&error);
  if (!shortcutsURL) {
    NSLog(@"Unable to locate the shortcuts file: %@", error.localizedDescription);
    return nil;
  }
  NSData *content = [NSData dataWithContentsOfURL:shortcutsURL];
  NSArray<NSDictionary *> *jsonArray = [NSJSONSerialization JSONObjectWithData:content
                                                                       options:0
                                                                         error:&error];
  if (!jsonArray) {
    NSLog(@"Deserializing shortcuts failed: %@", error.localizedDescription);
    return nil;
  }
  return shortcutsFromJsonObject(jsonArray);
}
```

[action](https://github.com/eczarny/spectacle/blob/4391dcc83b3d29842825260abd3827db59e3ec06/Spectacle/Sources/SpectacleShortcutJSONStorage.m#L7) set, but not used

### PR DESCRIPTION
**Pull request by twlz0ne**
I'm not sure that is appropriate, I don't know about Mac development, I'm just trying to fix the problem.

### CODE REVIEW

**Comment by twlz0ne** [comment]
close #630

**Comment by eczarny** [comment]
Thanks!

**Comment by twlz0ne** [comment]
@eczarny
There is a typo in commit message：530 => 630
My mistake 😖

**Comment by eczarny** [comment]
@twlz0ne no worries!

**Pull request merged**
